backend/backend/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings

from krapat import views as kviews


urlpatterns = [
    path("", kviews.index, name="index"),
    path("about", kviews.AboutView.as_view(), name="about"),
    path("contrib", kviews.ContribView.as_view(), name="contrib"),
    # area
    path("areas", kviews.AreasView.as_view(), name="areas"),
    path("area/<int:pk>", kviews.AreaView.as_view(), name="area"),
    # subarea
    path("subarea/<int:pk>", kviews.SubAreaView.as_view(), name="subarea"),
    # problem
    path("problem/<int:pk>", kviews.ProblemView.as_view(), name="problem"),
    # parking
    # path("parking/<int:pk>", kviews.ParkingView.as_view(), name="parking"),
    # path("admin/", admin.site.urls),
    path(f"admin_{settings.ADMIN_URL_SUFFIX}/", admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.urls import include

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    if settings.KRAPAT_ENABLE_DJANGO_DEBUG_TOOLBAR:
        urlpatterns += [
            path("__debug__/", include("debug_toolbar.urls")),
        ]

backend/krapat/models.py
from django.contrib.auth.models import User
from django.db import models

# from django.contrib.gis.db import models as gis_models


class Area(models.Model):

    """A climbing area e.g. Kerlouan

    An Area can have multiple SubArea
    """

    title = models.CharField(max_length=150)
    department = models.CharField(max_length=120)
    region = models.CharField(max_length=120)
    country = models.CharField(max_length=120)
    # TODO
    # longitude = models.DecimalField(max_digits=9, decimal_places=6)
    # latitude = models.DecimalField(max_digits=9, decimal_places=6)

    def __str__(self):
        return "{}: {}".format(self.pk, self.title)


class SubArea(models.Model):

    """A climbing sub area e.g. Crémiou 1

    A SubArea is a children of an Area
    """

    title = models.CharField(max_length=150)
    # rocks = models.ForeignKey(to=Rock, on_delete=models.CASCADE)
    area = models.ForeignKey(to=Area, related_name="subareas", on_delete=models.CASCADE)
    enabled = models.BooleanField(default=False)

    def __str__(self):
        return "{}: {}".format(self.pk, self.title)


# class Parking(models.Model):
#
#     """ A parking to access a given sub area"""
#
#     # TODO: same Parking for multiple subarea?
#
#     title = models.CharField(max_length=150)
#     subarea = models.ForeignKey(to=SubArea, related_name="parkings", on_delete=models.CASCADE, null=True, blank=True)
#
#     def __str__(self):
#         return self.title


# class Rock(models.Model):
#
#     """ One rock in a subarea, there can be multiple problems on a rock"""
#
#     title = models.CharField(max_length=150)
#     # FIXME: better field name
#     n = models.IntegerField()
#     subarea = models.ForeignKey(to=SubArea, related_name="rocks", on_delete=models.CASCADE)
#
#     def __str__(self):
#         return self.title


class CircuitColor(models.IntegerChoices):
    # Fontainebleau circuit colors
    WHITE = 0, "White"
    YELLOW = 1, "Yellow"
    ORANGE = 2, "Orange"
    BLUE = 3, "Blue"
    RED = 4, "Red"
    BLACK = 5, "Black"
    PURPLE = 6, "Purple"


# class Circuit(models.Model):
#     title = models.CharField(max_length=150)
#     color = models.IntegerField(choices=CircuitColor.choices, default=CircuitColor.BLUE)
#     # TODO: ?
#     # children = models.BooleanField(default=False)
#     subarea = models.ForeignKey(to=SubArea, related_name="circuits", on_delete=models.CASCADE)


# class Variant(models.Model):
#     rock = models.ForeignKey(to=Rock, related_name="variants", on_delete=models.CASCADE)


class ProblemGrade(models.IntegerChoices):
    G_UNKNOWN = 0, "?"
    G_2 = 1, "2"
    G_2A = 2, "2A"
    G_2B = 3, "2B"
    G_2C = 4, "2C"
    G_3 = 5, "3"
    G_3A = 6, "3A"
    G_3B = 7, "3B"
    G_3C = 8, "3C"
    G_4 = 9, "4"
    G_4A = 10, "4A"
    G_4B = 11, "4B"
    G_4C = 12, "4C"
    G_5 = 13, "5"
    G_5A = 14, "5A"
    G_5B = 15, "5B"
    G_5C = 16, "5C"
    G_6 = 17, "6"
    G_6A = 18, "6A"
    G_6B = 19, "6B"
    G_6C = 20, "6C"
    G_7 = 21, "7"
    G_7A = 22, "7A"
    G_7B = 23, "7B"
    G_7C = 24, "7C"
    G_8 = 25, "8"
    G_8A = 26, "8A"
    G_8B = 27, "8B"
    G_8C = 28, "8C"
    G_9 = 29, "9"
    G_9A = 30, "9A"
    G_9B = 31, "9B"
    G_9C = 32, "9C"


class ProblemGradeAddon(models.IntegerChoices):
    G_MINUS = 0, "-"
    G_PLUS = 1, "+"


# def properties_defaults():
#
#     return {
#         "sit_start": False,
#         "spotter_required": True,
#         "dyno": False
#     }


class Problem(models.Model):
    # fields
    title = models.CharField(max_length=150)
    description = models.TextField(null=True)
    order = models.PositiveIntegerField(null=True, blank=True)
    # published = models.BooleanField(default=False)
    # created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    # variants = models.ForeignKey(to="Problem", on_delete=models.SET_NULL)
    # variant = models.ForeignKey("self")
    # data = models.JSONField(null=True)
    subarea = models.ForeignKey(
        to=SubArea, related_name="problems", on_delete=models.CASCADE
    )
    # rock = models.ForeignKey(to=Rock, related_name="problems", null=True, blank=True, on_delete=models.CASCADE)
    # circuit = models.ForeignKey(to=Circuit, related_name="problems", null=True, blank=True, on_delete=models.CASCADE)
    # variant = models.ForeignKey(to=Variant, related_name="problems", null=True, blank=True, on_delete=models.CASCADE)

    grade = models.IntegerField(
        choices=ProblemGrade.choices, default=ProblemGrade.G_UNKNOWN
    )
    grade_addon = models.IntegerField(
        choices=ProblemGradeAddon.choices, default=None, null=True, blank=True
    )

    # problem properties
    # properties = models.JSONField(null=True, default=properties_defaults)

    def __str__(self):
        return "{}: {} - {}".format(
            self.pk,
            self.title,
            self.description
            if len(self.description) < 20
            else self.description[:20] + "...",
        )


class Image(models.Model):
    # title = models.CharField(max_length=150, null=True, blank=True)
    image = models.ImageField(upload_to="images")
    problem = models.ForeignKey(
        to=Problem,
        related_name="images",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    # rock = models.ForeignKey(to=Rock, related_name="images",
    #                          null=True, blank=True,
    #                          on_delete=models.CASCADE)

    width = models.PositiveIntegerField(default=0)
    height = models.PositiveIntegerField(default=0)
    # kind = ... # enum ?
    original = models.ForeignKey(
        to="self",
        null=True,
        blank=True,
        on_delete=models.DO_NOTHING,
        related_name="org",
    )
    order = models.PositiveIntegerField(default=0)

    def __str__(self):
        s = f"Image (id: {self.pk}) (size: {self.width}/{self.height}) for problem: {self.problem_id}"
        if self.original:
            s += f", original image: {self.original.pk}"

        return s

backend/krapat/forms.py
from django import forms

from .models import Area, SubArea, Problem, Image


class ProblemCreateForm(forms.ModelForm):
    class Meta:
        model = Problem
        # exclude = ("created_by",)
        labels = {"title": "Title"}
        fields = (
            "__all__"  # Or a list of the fields that you want to include in your form
        )


class AreaCreateForm(forms.ModelForm):
    class Meta:
        model = Area
        # exclude = ("created_by",)
        labels = {"title": "Title"}
        fields = (
            "__all__"  # Or a list of the fields that you want to include in your form
        )


class SubAreaCreateForm(forms.ModelForm):
    class Meta:
        model = SubArea
        # exclude = ("created_by",)
        labels = {"title": "Title"}
        fields = (
            "__all__"  # Or a list of the fields that you want to include in your form
        )


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ("image", "problem")  # "title",

backend/krapat/views.py
from django.views import generic
from django.shortcuts import render
from django.conf import settings
from django.db.models import Count

from .models import Area, SubArea, Problem, Image


def index(request):
    areas = []
    if settings.KRAPAT_AREAS_ON_INDEX_PAGE:
        areas = Area.objects.filter(pk__in=settings.KRAPAT_AREAS_ON_INDEX_PAGE)

    return render(request, "krapat/index.html", {"areas": areas})


class AreasView(generic.ListView):
    model = Area
    template_name = "krapat/areas.html"
    context_object_name = "areas"


class AreaView(generic.ListView):
    model = SubArea
    template_name = "krapat/area.html"
    context_object_name = "subareas"

    def get_queryset(self):
        subareas = (
            SubArea.objects.filter(area__id=self.kwargs["pk"], enabled=True)
            .annotate(Count("problems"))
            .select_related("area")
        )
        return subareas


class SubAreaView(generic.ListView):
    model = Problem
    template_name = "krapat/subarea.html"
    context_object_name = "problems"

    def get_queryset(self):
        problems = Problem.objects.filter(subarea__id=self.kwargs["pk"])
        return problems


class ProblemView(generic.DetailView):
    model = Problem
    template_name = "krapat/problem.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        # Original image is the first one
        # FIXME: this assumes that order is valid for an image and its resized version
        images = Image.objects.filter(problem=context["problem"]).order_by(
            "order", "original", "-width", "-height"
        )

        # Notes: here we have all images in db like
        #        image1, image 1 resized 1, .. image 1 resized N, image 2, image 2 resized 1 ...
        # src: image1, image 2
        # srcset: image1 resized N {WIDTH}w .. image1 resized 1 {WIDTH}w image 1 {WIDTH}w image2 resized N {WIDTH}w ...

        src = []
        srcset = []
        srcset_ = []
        for img in images:
            if img.original is None:
                if srcset_:
                    srcset.append(",".join(reversed(srcset_)))
                    srcset_ = []
                src.append(img.image.url)

            srcset_.append(f"{img.image.url} {img.width}w")

        if srcset_:
            srcset.append(",".join(reversed(srcset_)))

        # FIXME: remove context["images"] and cleanup template file
        # context["images"] = Image.objects.filter(problem=context["problem"])
        context["images"] = src
        context["src_iterator"] = zip(src, srcset)

        return context


class AboutView(generic.TemplateView):
    template_name = "krapat/about.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["discord_url"] = settings.DISCORD_URL
        return context


class ContribView(generic.TemplateView):
    template_name = "krapat/contrib.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["repo_url"] = settings.REPO_URL
        context["discord_url"] = settings.DISCORD_URL
        return context

backend/krapat/templates/krapat/about.html
{% extends "krapat/base.html" %}

{% block head_title %}
Krapat - About page
{% endblock %}

{% block page_content %}
<div class="px-4 pt-5 my-5 text-center border-bottom">
    <h1 class="display-4 fw-bold">
        A Propos
    </h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Krapat est d'abord né de la volonté d'illustrer le <a
                href="http://krimpadenn.fr/telechargements/viewdownload/9-kerlouan/65-les-blocs-de-kerlouan">
            topo de Kerlouan
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-link" viewBox="0 0 16 16">
                <path d="M6.354 5.5H4a3 3 0 0 0 0 6h3a3 3 0 0 0 2.83-4H9c-.086 0-.17.01-.25.031A2 2 0 0 1 7 10.5H4a2 2 0 1 1 0-4h1.535c.218-.376.495-.714.82-1z"/>
                <path d="M9 5.5a3 3 0 0 0-2.83 4h1.098A2 2 0 0 1 9 6.5h3a2 2 0 1 1 0 4h-1.535a4.02 4.02 0 0 1-.82 1H12a3 3 0 1 0 0-6H9z"/>
            </svg>
        </a>!</p>
    </div>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Mais le projet a mué avec l'envie de créer un site participatif et une
            <a href="{{ discord_url }}">communauté
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-discord" viewBox="0 0 16 16">
                    <path d="M13.545 2.907a13.227 13.227 0 0 0-3.257-1.011.05.05 0 0 0-.052.025c-.141.25-.297.577-.406.833a12.19 12.19 0 0 0-3.658 0 8.258 8.258 0 0 0-.412-.833.051.051 0 0 0-.052-.025c-1.125.194-2.22.534-3.257 1.011a.041.041 0 0 0-.021.018C.356 6.024-.213 9.047.066 12.032c.001.014.01.028.021.037a13.276 13.276 0 0 0 3.995 2.02.05.05 0 0 0 .056-.019c.308-.42.582-.863.818-1.329a.05.05 0 0 0-.01-.059.051.051 0 0 0-.018-.011 8.875 8.875 0 0 1-1.248-.595.05.05 0 0 1-.02-.066.051.051 0 0 1 .015-.019c.084-.063.168-.129.248-.195a.05.05 0 0 1 .051-.007c2.619 1.196 5.454 1.196 8.041 0a.052.052 0 0 1 .053.007c.08.066.164.132.248.195a.051.051 0 0 1-.004.085 8.254 8.254 0 0 1-1.249.594.05.05 0 0 0-.03.03.052.052 0 0 0 .003.041c.24.465.515.909.817 1.329a.05.05 0 0 0 .056.019 13.235 13.235 0 0 0 4.001-2.02.049.049 0 0 0 .021-.037c.334-3.451-.559-6.449-2.366-9.106a.034.034 0 0 0-.02-.019Zm-8.198 7.307c-.789 0-1.438-.724-1.438-1.612 0-.889.637-1.613 1.438-1.613.807 0 1.45.73 1.438 1.613 0 .888-.637 1.612-1.438 1.612Zm5.316 0c-.788 0-1.438-.724-1.438-1.612 0-.889.637-1.613 1.438-1.613.807 0 1.451.73 1.438 1.613 0 .888-.631 1.612-1.438 1.612Z"/>
                </svg>
            </a>.
        </p>
    </div>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">N'hésitez pas à venir <a href="{% url 'contrib' %}">contribuer</a> (ou juste discuter)!</p>
    </div>
</div>
{% endblock page_content %}

backend/krapat/templates/krapat/area.html
{% extends "krapat/base.html" %}

{% block head_title %}
Krapat - {{ area.title }}
{% endblock %}

{% block page_content %}

<div class="container px-4 py-5" id="custom-cards">

    <h2 class="pb-2 border-bottom">Sub Areas</h2>
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">

        {% for subarea in subareas.all %}
        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('unsplash-photo-1.jpg');">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                    <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">
                        <!-- Note: stretched-link is to make the card click'able -->
                        <a href="{% url 'subarea' pk=subarea.pk %}" class="text-decoration-none stretched-link">
                            {{ subarea.title }}
                        </a>
                    </h2>
                    <ul class="d-flex list-unstyled mt-auto">
                        <li class="me-auto">
                            <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
                        </li>
                        <li class="d-flex align-items-center me-3">
                            <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                            <small>{{ subarea.area.title }}</small>
                        </li>
                        <li class="d-flex align-items-center">
                            <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                            <small>{{ subarea.problems__count }} problems</small>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <h2 class="pb-2 border-bottom">Parking</h2>
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
    </div>
</div>

{% endblock %}

backend/krapat/templates/krapat/area_create.html
<head>
    {{ form.media }}
</head>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="Submit">
    <a href="{% url 'areas' %}" class="btn btn-secondary">Cancel</a>
</form>

backend/krapat/templates/krapat/areas.html
{% extends "krapat/base.html" %}

{% block head_title %}
Krapat - Areas
{% endblock %}

{% block page_content %}

<div class="container px-4 py-5" id="custom-cards">
    <h2 class="pb-2 border-bottom">Areas</h2>
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">

        {% for area in areas %}
        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('unsplash-photo-1.jpg');">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                    <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">
                        <!-- Note: stretched-link is to make the card click'able -->
                        <a href="{% url 'area' pk=area.pk %}" class="text-decoration-none stretched-link">
                        {{ area.title }}
                        </a>
                    </h2>
                    <ul class="d-flex list-unstyled mt-auto">
                        <li class="me-auto">
                            <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
                        </li>
                        <li class="d-flex align-items-center me-3">
                            <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                            <small>{{ area.department }}</small>
                        </li>
                        <li class="d-flex align-items-center">
                            <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                            <small>{{ area.region }}</small>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>


{% comment %}
<h1>@@ Bouldering areas @@</h1>
{% if not areas %}
    <p>No areas are available. </p>
    <li><a href="{% url 'area_add' %}">Create a new area BB</a></li>
{% else %}
<ul>
    <li><a href="{% url 'area_add' %}">Create a new area</a></li>
    {% for area in areas %}
        <li><a href="/area/{{ area.pk }}">{{ area }}</a> - <a href="/area/{{ area.pk }}/update">edit</a></li>
        <ul>
            <li><a href="/subarea/add/{{ area.pk }}">Create a new subarea</a></li>
            {% for subarea in area.subareas.all %}
            <li><a href="/subarea/{{ area.pk }}">{{ subarea }}</a> - <a href="/subarea/{{ area.pk }}/update">edit</a></li>
                <ul>
                <li>Found {{ subarea.problems.count }} problem(s)</li>
                <li>
                    <a href="/problem/add/{{ subarea.pk }}">Add problem</a>
                </li>
                <li>
                    <a href="/problems/{{ subarea.pk }}">All problems</a>
                </li>
                <li>Circuits:</li>
                <ul>
                </ul>
            </ul>

            {% endfor %}
        </ul>

    {% endfor %}
</ul>
{% endif %}

<hr>

{% endcomment %}

{% endblock %}

backend/krapat/templates/krapat/contact.html
<h1>Hello! You're at the krapat contact page.</h1>

backend/krapat/templates/krapat/image_upload.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
   {{ form.as_p }}
  <button type="submit">Upload</button>
</form>

{% if img_obj %}
  <h3>Succesfully uploaded : {{img_obj.title}}</h3>
  <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
{% endif %}

backend/krapat/templates/krapat/problem.html
{% extends "krapat/base.html" %}

{% block head_title %}
Krapat - {{ problem.title }}
{% endblock %}

{% block page_content %}
<div class="px-4 pt-5 my-5 text-center border-bottom">
    <h1 class="display-4 fw-bold">
        {% if problem.get_grade_addon_display %}
        {{ problem.title }} ({{problem.get_grade_display}}{{problem.get_grade_addon_display}})
        {% else %}
        {{ problem.title }} ({{problem.get_grade_display}})
        {% endif %}
    </h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">{{ problem.description }}</p>
    </div>
</div>

<div id="carousel_problem" class="carousel slide" data-bs-ride="carousel">

    <div class="carousel-indicators">
        {% for img in images %}
        {% if forloop.counter0 == 0 %}
        <button type="button" data-bs-target="#carousel_problem" data-bs-slide-to="{{ forloop.counter0 }}" class="active" aria-current="true" aria-label="Slide {{ forloop.counter0 }}">
        </button>
        {% else %}
        <button type="button" data-bs-target="#carousel_problem" data-bs-slide-to="{{ forloop.counter0 }}" aria-label="Slide {{ forloop.counter0 }}">
        </button>
        {% endif %}
        {% endfor %}
    </div>

    <div class="carousel-inner">
        {% for src, srcset in src_iterator %}
        {% if forloop.counter0 == 0 %}
        <div class="carousel-item active">
        {% else %}
        <div class="carousel-item">
        {% endif %}

            {% comment %}
            w-100 && d-block:
            https://getbootstrap.com/docs/5.2/components/carousel/#slides-only
            {% endcomment %}

            {% comment %}
            <img src="{{ img.image.url }}"
                 srcset="/media/images/cr%C3%A9miou_1_alien_1_w600_optim.jpg 600w, {{ img.image.url }} 1536w"
                 class="d-block w-100"
                 alt="..."
                 loading="lazy"
                 decoding="async"
            >
            {% endcomment %}

            <img src="{{ src }}"
                 srcset="{{ srcset }}"
                 class="d-block w-100"
                 alt="..."
                 loading="lazy"
                 decoding="async"
            >

        </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>


{% endblock %}

backend/krapat/templates/krapat/problem_create.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="Submit">
    <a href="{% url 'subarea' pk=subarea.pk %}" class="btn btn-secondary">Cancel</a>
</form>

backend/krapat/templates/krapat/problems.html
{% comment %}
<h1>@@ Problems for {{ request.user }} @@</h1>
{% endcomment %}
<h1>@@ Problems for {{ subarea.title }} @@</h1>
{% if not problems %}
    <p>No problems are available. </p>
    <li><a href="/problem/add/{{ subarea.pk }}">Create a new problem</a></li>
{% else %}
<ul>
    <li><a href="/problem/add/{{ subarea.pk }}">Create a new problem</a></li>
    {% for problem in problems %}
    <li>
        <a href="/problem/{{ problem.pk }}">{{ problem }}</a> - <a href="/problem/{{ problem.pk }}/update">edit</a>
        - <a href="/image_upload">upload image</a>
    </li>
    {% endfor %}
</ul>
{% endif %}

<hr>

backend/krapat/templates/krapat/subarea.html
{% extends "krapat/base.html" %}

{% block head_title %}
Krapat - {{ subarea.title }}
{% endblock %}

{% block page_content %}

{% comment %}
<a href="{% url 'problem_add' subarea_pk=subarea.pk %}" class="btn btn-outline-dark">
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
  </svg>
  <span>Add problem</span>
</a>

<hr>
{% endcomment %}

{% comment %}
<p><a href="#">View on maps</a></p>
<hr>
{% endcomment %}
<ul class="list-group">
  {% for problem in problems.all %}
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="{% url 'problem' pk=problem.pk %}" class="text-decoration-none stretched-link">{{ problem.title }}</a>
    {% if problem.get_grade_addon_display %}
    <span class="badge bg-primary rounded-pill">{{ problem.get_grade_display }}{{ problem.get_grade_addon_display }}</span>
    {% else %}
    <span class="badge bg-primary rounded-pill">{{ problem.get_grade_display }}</span>
    {% endif %}
  </li>
  {% endfor %}
</ul>
<hr>

{% endblock %}

backend/krapat/templates/krapat/subarea_create.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="Submit">
    <a href="{% url 'area' pk=area.pk %}" class="btn btn-secondary">Cancel</a>
</form>